CREATE USER IPL_OWNER
IDENTIFIED BY "<CHANGE_ME>";

GRANT CREATE SESSION TO IPL_OWNER;

GRANT
    CREATE TABLE,
    CREATE VIEW,
    CREATE SEQUENCE,
    CREATE PROCEDURE,
    CREATE TRIGGER,
    CREATE TYPE,
    CREATE SYNONYM
TO IPL_OWNER;

ALTER USER IPL_OWNER
QUOTA UNLIMITED ON USERS;